[project]
name = "webapp"
version = "0.1.0"
description = "Simple webapp for AitM attack demo."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "itsdangerous>=2.2.0",
    "python-multipart>=0.0.20",
    "starlette>=0.49.3",
    "uvicorn>=0.38.0",
]
